/**
 * Ingest a portfolio hand-off → generated Defense cards (+ ties if a qid→concepts
 * map is supplied). Validates at the boundary, writes reviewable *.gen.json next
 * to the input, and prints the drop/flag report. Does NOT touch catalog.ts —
 * wiring the survivors in is a deliberate, reviewed second step.
 *
 * Usage:
 *   tsx scripts/ingest-portfolio.ts <handoff.json> [--paths <ls-files.txt>] [--concepts <qid-map.json>]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import {
  validateHandoff,
  summarizeReport,
  toDefenseItems,
  toTieMap,
} from "../lib/portfolio/index";

function arg(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : undefined;
}
function readJson(p: string): unknown {
  return JSON.parse(readFileSync(p, "utf8"));
}

const handoffPath = process.argv[2];
if (!handoffPath || handoffPath.startsWith("--")) {
  console.error("usage: tsx scripts/ingest-portfolio.ts <handoff.json> [--paths f.txt] [--concepts m.json]");
  process.exit(1);
}

const raw = readJson(handoffPath);
const pathsFile = arg("--paths");
const knownPaths = pathsFile
  ? readFileSync(pathsFile, "utf8").split(/\r?\n/).map((s) => s.trim()).filter(Boolean)
  : undefined;

const { clean, report } = validateHandoff(raw, { knownPaths });
console.log(summarizeReport(report));

const { items, provisional } = toDefenseItems(clean);
console.log(`\nDefense cards generated: ${items.length}` + (provisional.length ? ` (${provisional.length} provisional — review)` : ""));
for (const it of items) {
  const flag = provisional.includes(it.id) ? " ⚠" : "";
  console.log(`  • [${it.id}] ${it.title} · ${it.roleTrack}${it.core ? " · core" : ""}${flag}`);
}

const outDir = dirname(handoffPath);
const stem = basename(handoffPath).replace(/\.json$/, "").replace(/[.-]pass1$/, "");

// JSON for inspection + a typed TS module catalog.ts imports (re-ingest = regen).
const defenseOut = join(outDir, `${stem}.defense.gen.json`);
writeFileSync(defenseOut, JSON.stringify({ items, provisional }, null, 2));
const tsOut = join(outDir, `${stem}.defense.gen.ts`);
writeFileSync(
  tsOut,
  `// GENERATED by scripts/ingest-portfolio.ts from ${basename(handoffPath)} — do not edit by hand.\n` +
    `import type { FileDefenseItem } from "@waypoint/practice-types";\n\n` +
    `export const DEFENSE: FileDefenseItem[] = ${JSON.stringify(items, null, 2)};\n`,
);
console.log(`\n→ ${defenseOut}\n→ ${tsOut}`);

const conceptsFile = arg("--concepts");
if (conceptsFile) {
  const map = readJson(conceptsFile) as Record<string, string[]>;
  const ties = toTieMap(clean, map);
  const n = Object.keys(ties).length;
  console.log(`Ties generated: ${n} / ${Object.keys(map).length} questions had a matching site`);
  const tiesOut = join(outDir, `${stem}.ties.gen.json`);
  writeFileSync(tiesOut, JSON.stringify(ties, null, 2));
  console.log(`→ ${tiesOut}`);
} else {
  console.log("\n(no --concepts map given → ties skipped; hand me question-concepts.json to generate them)");
}
